config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  devise_for :users, controllers: {
              registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :stores do
    resources :products
    resources :orders do
              collection do
                patch 'payed_orders'
                get 'historial'
              delete 'empty_cart'
            end
            member do
              patch 'confirm_order'
              patch 'delivered_order'
            end
          end
      # buscar rutas custom to: as:

  end
  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'

    end
  end

  root to: 'stores#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :users
  geocoded_by :address
  after_validation :geocode
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /stores
  # GET /stores.json
  def index
    if params[:latitude].present? && params[:longitude].present?
    @stores = Store.near(
      [params[:latitude], params[:longitude]],
      10_000,
      units: :km
    )
  elsif current_user.present?
    # @stores = Store.near(
    #  current_user.address,
    #  10_000,
    #  units: :km
    # )
    # no quiere funcar
  else
    @stores = Store.first(10)
  end


    @hash = Gmaps4rails.build_markers(@stores) do |store, marker|
      marker.lat store.latitude
      marker.lng store.longitude
    end

  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @orders = Order.where(store_id: @store.id, user: current_user, payed: 'cart')
    @store = Store.find(params[:id])
    @total = 0
    @price_quantity = @orders.pluck(:price, :quantity)
    @price_quantity.each do |price|
      @total += (price[0]*price[1]).to_i
    end

  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])


    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :rut)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_about_us.html.erb
<div class="container">
  <button class="btn black btn-lg btn-sm fixed-top" style="margin: 35.6rem 0 0 0 " data-toggle="modal" data-target="#canasta">Quienes somos  <i class="fa fa-shopping-basket"></i>  </button>

  <div class="modal micanasta" id="canasta">
    <div class="right white b-t" style="width: 50vh">
      <div class="row-col"><a data-dismiss="modal" class="pull-right text-muted text-lg p-a-sm m-r-sm">×</a>

        <div class="p-a b-b">
          <span class="h5">Nosotros</span>
        </div>
        <div class="container" style="overflow: scroll;">
          <div class="row">
            <div class="col-lg-11" style="overflow: scroll; margin: auto;">
              <h2>No mas filas.</h2>
              <h3> ¿Por que hacer la fila para pedir tu comida y luego retirarla?</h3>
              <h4>Para eso existimos nosotros ! <br>Solo te pedimos acceso a tu ubicación, para señalarte los locales mas cercanos y realizar tu pedido directamente desde nuestra plataforma, asi el tiempo que perdias en esperar en la fila para pagar y luego retirar tu pedido, lo podrás utilizar en lo que tu desees.  </h4>
              <h3> ¿Como funciona?</h3>
              <h4> Solo debes registrarte en nuestra plataforma, ver cual es el local que deseas pedir tu comida, selecciona los productos, realiza el pago mediante Paypal y luego espera a que la tienda te avise cuando esta listo tu pedido</h4>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/stores/_admin_product.html.erb
  <div class="row">
    <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11" style="margin: 3rem auto 0 auto;">
      <table class="table table-bordered table-dark text-center">
        <thead>
          <h1 class="text-center text-white">Productos</h1>
          <h1 class="text-center"><%= link_to 'New Product', new_store_product_path(@store), class: 'btn btn-light btn-lg' %></h1>
          <tr>
            <td>Image</td>
            <td>Name</td>
            <td>description</td>
            <td>Price</td>
            <td>Edit</td>
            <td>Destroy</td>
          </tr>
        </thead>
        <tbody>
          <% @store.products.each do |product| %>
            <tr scope="row">
              <td><%= image_tag 'shawarma.jpg', class:"card-img-top rounded", alt:"Card image cap"%></td>
              <td><p class="font-weight-bold" style="margin-top: 2rem;" ><%= product.name %></p></td>
              <td><p class="font-weight-bold" style="margin-top: 2rem;" ><%= product.description%></p></td>
              <td><p class="font-weight-bold" style="margin-top: 2rem;" ><%= product.price %></p></td>
              <td><p class="btn btn-info btn-lg" style="margin-top: 1rem;" ><%= link_to 'Edit', edit_store_product_url(@store, product), class:'text-white' %></p>             </td>
              <td><p class="btn btn-danger btn-lg" style="margin-top: 1rem;" ><%= link_to 'Destroy', store_product_path(@store, product), method: :delete, data: { confirm: 'Are you sure?' }, class:'text-white' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="text-center" style="margin-bottom: 6rem;">
    <h1><%= link_to 'Back', stores_path, class:'btn btn-lg btn-light'%></h1>
  </div>

app/views/stores/_admin_store.html.erb
  <div class="row">
    <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11 " style="margin: 3rem auto 0 auto;">
      <table class="table table-bordered table-dark text-center">
        <thead>
          <h1 class="text-center text-white">Mi tienda</h1>
          <tr>
            <td><h3 class="text-white">Name</h3></td>
            <td><h3 class="text-white">Image</h3></td>
            <td><h3 class="text-white">Edit</h3></td>
            <td><h3 class="text-white">Menu</h3></td>
            <td><h3 class="text-white">History delivered</h3>
            <td><h3 class="text-white">Pending Orders</h3></td>
          </tr>
        </thead>
        <tbody>
          <% @stores.each do |store| %>
            <% if current_user.local_admin? and current_user.store == store %>

              <tr scope="row">
                <td><h3 class="text-white" style="margin: 2.5rem 0 0 0;"><%= store.name %></h3></td>
                <td><%= image_tag 'shawarma.jpg', class:"rounded", style:"max-width: 25%; min-width: 7rem;"%></td>
                <td><%= link_to 'Edit', edit_store_path(store),class:" btn btn-info btn-lg text-white", style:"margin: 2rem 0 0 0;" %></td>
                <td><%= link_to 'Menu', store, class:"btn btn-info btn-lg text-white", style:"margin: 2rem 0 0 0;" %></td>
                <td><%= link_to "History delivered", historial_store_orders_path(current_user.store_id), class:"btn btn-info btn-lg text-white", style:"margin: 2.2rem 0 0 0;"%></td>
                <td><%= link_to "Pending Orders", store_orders_path(current_user.store_id), class:"btn btn-info btn-lg text-white", style:"margin: 2rem 0 0 0;"%></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/stores/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 form-stores bg-light">
      <%= form_with(model: store, local: true) do |form| %>
        <% if store.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

            <ul>
            <% store.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <h3><%= form.label :name %></h3>
          <%= form.text_field :name %>
        </div>

        <div class="form-group">
          <h3><%= form.label :address %></h3>
          <%= form.text_field :address %>
        </div>

        <div class="form-group">
          <h3><%= form.label :rut%></h3>
          <%= form.text_field :rut %>
        </div>
        <div class="form-group">
          <h3><%= form.label :image %></h3>
          <%= form.text_field :image %>
          <h5><%= form.file_field :image, id: :image  %></h5>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/stores/_nil_product.html.erb
<%= render 'layouts/carousel' %>
<div class="container">
  <div class="row">
      <div class=" col-md-12 nombretienda">
        <h1 class="text-center text-white"><%= @store.name %></h1>
        <h1 class="text-center"><%= link_to 'carrito', store_orders_path(@store), class: 'btn btn-danger btn-lg text-white'%></h1>
      </div>

    <div class=" col-md-12 tituloproductos">
        <h1 class="text-center text-white">Products</h1>
    </div>
      <% @store.products.each do |product| %>
          <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 card-deck">
              <div class="card">
                <%= image_tag 'shawarma.jpg', class:"card-img-top rounded", alt:"Card image cap"%>
                <div class="card-body">
                  <h5 class="card-title"><%= product.name %></h5>
                  <p class="card-text"><%= product.description%></p>
                </div>
                <div class="card-footer text-center">
                  <h2 class="text-white"><%= number_to_currency(product.price, precision: 0, seperator: ",", delimiter: ".")%></h2>
                  <small class="text-muted"><%= link_to 'Agregar ', store_orders_path(@store, product_id: product), class: 'btn btn-danger text-white', remote: true, method: :post %></small>
                </div>
              </div>
          </div>
    <% end %>
  </div>
</div>
<%= render 'layouts/shopping_cart' %>
<div class="text-center" style="margin-bottom: 6rem;">
  <h1><%= link_to 'Back', stores_path, class:'btn btn-lg text-white btn-dark'%></h1>
</div>

app/views/stores/_nil_store.html.erb
<%= render 'layouts/carousel' %>
<div class="container">
  <div class="row">
    <div class="col-lg-12" style="margin: auto 0 10rem 0;">
        <table class="table-striped table-dark">
          <tr>
            <h1 class="text-center text-white" style="margin: 3rem 0 4rem 0;">Tiendas</h1>
          </tr>
          <tbody class="view-stores-nil">
            <% @stores.each do |store| %>
              <tr>
                <td><%= image_tag 'shawarma.jpg', class:"rounded float-left", style:"max-width: 25%; min-width: 7rem;"%></td>
                <td><h3 style="margin: 2rem auto 2rem auto;" class="text-left"><%= link_to store.name, store, class:"text-white"%></h3></td>
                <td><p style="margin: 1.5rem 0 auto 0;" ><%= link_to 'Menu', store, class:"btn btn-info btn-lg text-white float-right" %></p></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</div>

app/views/stores/_store.html.erb
<tr scope="row">
    <td><h3 style="margin-top: 1rem;"  class="text-primary"><%= link_to store.name, store%></h3></td>
  <td>
    <p class="btn btn-primary btn-lg" style="margin-top: 1rem;" ><%= link_to 'Menu', store %></p>
    <p class="btn btn-primary btn-lg" style="margin-top: 1rem;" ><%= link_to 'Edit', edit_store_path(store) %></p>
    <p class="btn btn-primary btn-lg" style="margin-top: 1rem;" ><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </td>
</tr>

app/views/stores/edit.html.erb
<h1 class="text-center text-white" style="margin: 5rem 0 2rem 0;">Editing Store</h1>
<%= render 'form', store: @store %>
<div class="text-center">
  <h1> <%= link_to 'Menu', @store, class:'btn btn-light btn-lg ' %> <%= link_to 'Back', stores_path, class:'btn btn-light btn-lg '%></h1>
</div>

app/views/stores/index.html.erb
<% if user_signed_in? %>
  <% if current_user.local_admin? %>
    <%= render 'admin_store' %>
  <% else %>
    <%= render 'nil_store' %>
    <%= render 'about_us' %>
  <% end %>
<% else %>
  <%= render 'nil_store' %>
  <%= render 'about_us' %>    
<% end %>

  <script>
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      center: new google.maps.LatLng({lat: -34, lng: -33}),
      zoom: 4
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    google.maps.event.addListener(handler.getMap(), "click", function(){
     console.log("hola");
    });
    google.maps.event.addListener(handler.getMap(), "center_changed", function(){
     var latitude = handler.getMap().getCenter().lat();
     var longitude = handler.getMap().getCenter().lng();
     $.ajax({
       url: '/stores',
       type: 'GET',
       dataType: 'script',
       data: {latitude: latitude, longitude: longitude }
     })
      });
  }
);
  </script>

app/views/stores/index.js.erb
console.log("este si ctm ");
$('.carousel').carousel({
  interval: 2000
})
$("#stores-grl").html("<%= j render @stores %>")

app/views/stores/new.html.erb
<h1 class="text-center text-white" style="margin: 5rem 0 2rem 0;">New Store</h1>
<%= render 'form', store: @store %>
<div class="text-center">
  <h1><%= link_to 'Back', stores_path, class:'btn btn-light btn-lg '%></h1>
</div>

app/views/stores/show.html.erb
  <% if user_signed_in? %>
    <% if current_user.local_admin?%>
      <div class="">
        <%= render 'stores/admin_product' %>
      </div>
    <% else %>
      <div class="" id="mycart">
        <%= render 'stores/nil_product' %>
      </div>
    <% end %>
  <% else %>
    <div class="">
      <%= render 'stores/nil_product' %>
    </div>
  <% end %>