config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  devise_for :users, controllers: {
              registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :stores do
    resources :products
    resources :orders do
              collection do
                patch 'payed_orders'
                get 'historial'
              delete 'empty_cart'
            end
            member do
              patch 'confirm_order'
              patch 'delivered_order'
            end
          end
      # buscar rutas custom to: as:

  end
  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'

    end
  end

  root to: 'stores#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :billing, optional: true
  enum payed: [:cart, :payed, :completed, :delivered ]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

# frozen_string_literal: true
  def empty_cart
    @store = Store.find(params[:store_id])
    @set_orders = Order.where(user: current_user, store_id: @store.id)
    @set_orders.destroy_all
    redirect_to store_orders_path(@store),  notice: 'Se ha vaciado su bandeja'
  end

  def create

    @store = Store.find(params[:store_id])
    @product = Product.find(params[:product_id])
    @cart = current_user.cart

    if @cart.pluck(:product_id).include?(params[:product_id].to_i)
      product = current_user.orders.find_by(product_id: params[:product_id], payed: 0)
      product.quantity += 1
      @order = product
    else
      product = current_user.orders.build(product_id: @product.id, price: @product.price, payed: 'cart')
      @order = Order.new(product_id: @product.id, user: current_user, store_id: @store.id, price: @product.price, quantity: 1)
    end
    @orders = Order.where(store_id: @store.id, user: current_user, payed: 'cart')
    respond_to do |format|
      if @order.save
        @r =  'Tu producto fue agregado al carro!'
        format.js #,  {notice: 'Tu producto fue agregado al carro!'}
      else
        @r = 'Intenta nuevamente CTM!'
        format.js #,  {alert: 'Intenta nuevamente CTM!'}
      end
    end
  end

  def index
    @store = Store.find(params[:store_id])
    if current_user.local_admin?
      @completeds =  Order.where(store_id: @store.id, payed: 'completed')
      @orders = Order.where("payed= ? and store_id = ?", 1, @store.id)
    else
      @completeds =  Order.where(store_id: @store.id, user: current_user, payed: 'completed')
      @inprocess = Order.where(store_id: @store.id, user: current_user, payed: 'payed')
      @orders = Order.where(store_id: @store.id, user: current_user, payed: 'cart')
    end
    @products = @orders.map do |order|
    @products = Product.find(order.product.id)
    end
    @total = 0
    @price_quantity = @orders.pluck(:price, :quantity)
    @price_quantity.each do |price|
      @total += (price[0]*price[1]).to_i
    end
  end

  def destroy

    @order = current_user.orders.find(params[:id])
        respond_to do |format|
        if @order.destroy
          format.html { redirect_to store_orders_path(params[:store_id]), notice: 'eliminado exitosamente'}
          format.js
        else
          format.html { redirect_to store_orders_path(params[:store_id]), notice: 'no pudimos eliminar tu producto'}
          format.js
      end
    end
  end
  def payed_orders
    @orders = current_user.cart.update_all("payed = 1")
    redirect_to store_orders_path(params[:store_id])
  end

  def confirm_order
    @order = Order.find(params[:id])
    @order.payed = 'completed'
    @order.save
    redirect_to store_orders_path(params[:store_id])
  end

  def delivered_order
    @order = Order.find(params[:id])
    @order.payed = 'delivered'
    @order.save
    redirect_to store_orders_path(params[:store_id])
  end
  def historial
    @store = Store.find(params[:store_id])
    @orders=  Order.where(store_id: @store.id, payed: 'delivered')
  end

  private



  def set_cart
    @setcart = current_user.cart
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_admin_local.html.erb
<div class="">
  <div class="row">
    <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11" style="margin: 3rem auto 0 auto ;">
      <table class="table table-bordered table-dark text-center">
        <tr>
          <h1 class="text-center text-white"> <%= @store.name %></h1>
          <th class="text-center">
            Cliente
          </th>
          <th class="text-center">
            Producto
          </th>
          <th class="text-center">
            Description
          </th>
          <th class="text-center">
            Valor Unitario
          </th>
          <th class="text-center">
            Cantidad
          </th>
          <th class="text-center">
            Subtotal
          </th>
          <th class="text-center">
            Estado
          </th>
        </tr>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= order.user.name %>
            </td>
            <td>
              <%= order.product.name %>
            </td>
            <td>
              <%= order.product.description %>
            </td>
            <td>
              <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <%= order.quantity %>
            </td>
            <td>
              <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <%= link_to 'completado', confirm_order_store_order_path(@store, order), class: "btn btn-info btn-sm text-white", style:"margin: 0.8rem auto 0.8rem auto", method: :patch%>
            </td>
        <% end %>
        <% @completeds.each do |order| %>
          <tr>
            <td>
              <%= order.user.name %>
            </td>
            <td>
              <%= order.product.name %>
            </td>
            <td>
              <%= order.product.description %>
            </td>
            <td>
              <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <%= order.quantity %>
            </td>
            <td>
              <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <%= link_to 'Entregar', delivered_order_store_order_path(@store, order), class: "btn btn-info btn-sm text-white", style:"margin: 0.8rem auto 0.8rem auto", method: :patch%>
            </td>
        <% end %>
      </table>
      <div class="text-center">
        <h1><%= link_to 'Back', stores_path, class:'btn btn-light btn-lg '%></h1>
      </div>
    </div>
  </div>
</div>

app/views/orders/_user.html.erb
<div class="row">
  <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11" style="margin: 3rem auto 0 auto;">
    <table class="table table-bordered table-dark text-center">
      <h1 class="text-center text-white"><%= @store.name %></h1>
      <tr>
        <th class="text-center">
          Producto
        </th>
        <th class="text-center">
          Valor Unitario
        </th>
        <th class="text-center">
          Cantidad
        </th>
        <th class="text-center">
          Subtotal
        </th>
        <th class="text-center">
          Estado
        </th>
      </tr>
      <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.product.name %>
        </td>
        <td>
          <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
        </td>
        <td>
          <%= order.quantity %>
        </td>
        <td>
          <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
        </td>
        <td>
          No pagado <%= link_to 'Borrar', store_order_path(@store.id, order), class: "btn btn-danger btn-sm text-white", style:"margin: 0.8rem auto 0.8rem auto", method: :delete %>
        </td>
        <% end %>
        <% @inprocess.each do |order| %>
        <tr>
          <td>
            <%= order.product.name %>
          </td>
          <td>
            <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
          </td>
          <td>
            <%= order.quantity %>
          </td>
          <td>
            <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
          </td>
          <td>
            <p>En proceso</p>
          </td>
          <% end %>
          <% @completeds.each do |order| %>
          <tr>
            <td>
              <%= order.product.name %>
            </td>
            <td>
              <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <%= order.quantity %>
            </td>
            <td>
              <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
            </td>
            <td>
              <p>Retirar pedido</p>
            </td>
          </tr>
          <% end %>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th class="text-center">No Pagado: <%= number_to_currency(@total, precision: 0, seperator: ",", delimiter: ".")%></th>
          </tr>
        </table>
      </div>
      <div class="col-11 col-sm-11 col-md-4 col-lg-4 col-xl-4 text-center" style="margin-bottom: 1rem;">
        <%= link_to "Continuar comprando", store_path(@store.id), class: "btn btn-info btn-lg text-white" %>
      </div>


      <div class="col-11 col-sm-11 col-md-4 col-lg-4 col-xl-4 text-center" style="margin-bottom: 1rem;">
        <%= link_to "Confirmar Compra", pre_pay_billings_path ,class: "btn btn-info btn-lg text-white" %>
      </div>
      <div class="col-11 col-sm-11 col-md-4 col-lg-4 col-xl-4 text-center" style="margin-bottom: 1rem;">
        <%= link_to "Vaciar Carro", empty_cart_store_orders_path(@store), class: "btn btn-info btn-lg text-white", method: :delete %>
      </div>

  <tr>
    <tr>
    <th></th>
    <th></th>
    <th></th>
    <th><h3 class="text-white text-center"></h3></th>
    <th><h3 class="text-white text-center"></h3></th>
    <th>

    </th>
    </tr>

  </table>

app/views/orders/create.js.erb
console.log("<%=j @r %>")
$('#mycart').html(" <%=j render 'stores/nil_product', orders: @orders  %>")

app/views/orders/destroy.js.erb
var ele = $("#order-<%= @order.id %>")
ele.toggle(400);
alert(ele.data("value"))
var value = $("#delete").text()

$("#delete").text(parseInt(value) - parseInt(ele.data("value")))

app/views/orders/historial.html.erb
<div class="row">
  <div class="col-11 col-sm-11 col-md-11 col-lg-11 col-xl-11" style="margin: 3rem auto 0 auto ;">
    <table class="table table-bordered table-dark text-center">
    <h1 class="text-center text-white"> <%= @store.name %></h1>
    <tr class="text-center">
      <th class="text-center">
        Cliente
      </th>
      <th class="text-center">
        Producto
      </th>
      <th class="text-center">
        Valor Unitario
      </th>
      <th class="text-center">
        Cantidad
      </th>
      <th class="text-center">
        Total
      </th>
      <th class="text-center">
        Estado
      </th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td>
          <%= order.user.email %>
        </td>
        <td>
          <%= order.product.name %>
        </td>
        <td>
          <%= number_to_currency(order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
        </td>
        <td>
          <%= order.quantity %>
        </td>
        <td>
          <%= number_to_currency(order.quantity * order.product.price, precision: 0, seperator: ",", delimiter: ".")%>
        </td>
        <td>
          <p>Entregado</p>
        </td>
    <% end %>
    </table>
    <div class="text-center">
      <h1><%= link_to 'Back', stores_path, class:'btn btn-light btn-lg '%></h1>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<% if user_signed_in? %>
  <% if current_user.local_admin? %>
    <%= render 'admin_local' %>
  <% else %>
    <%= render 'user' %>
  <% end %>
<% end %>