config/routes.rb
Rails.application.routes.draw do


  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'geocoder/findaddress'
  devise_for :users, controllers: {
              registrations: 'users/registrations',
              :omniauth_callbacks => "users/omniauth_callbacks"
  }
  resources :stores do
    resources :products
    resources :orders do
              collection do
                patch 'payed_orders'
                get 'historial'
              delete 'empty_cart'
            end
            member do
              patch 'confirm_order'
              patch 'delivered_order'
            end
          end
      # buscar rutas custom to: as:

  end
  resources :billings, only: [:index] do
    collection do
      get 'pre_pay'
      get 'execute'

    end
  end

  root to: 'stores#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :store
  has_many :orders, dependent: :destroy
  # has_many :users, through: :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @store = Store.find(params[:store_id])
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @store = Store.find(params[:store_id])
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @store = Store.find(params[:store_id])
    @product.store = @store

    respond_to do |format|
      if @product.save
        format.html { redirect_to store_path(@store), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @store = Store.find(params[:store_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to store_path(@store), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @store = Store.find(params[:store_id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to store_path(@store), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image, :price, :store_id, :remote_image_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
  <div class="row">
    <div class=" col-md-10 form-products bg-light">
      <%= form_for([@store, @product], local: true) do |form| %>
        <% if product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
            <% product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <h3><%= form.label :name %></h3>
           <%= form.text_field :name %>

        </div>

        <div class="form-group">
          <h3><%= form.label :description %></h3>
          <%= form.text_area :description %>

        </div>


        <div class="form-group">
          <h3><%= form.label :price %></h3>
          <%= form.text_field :price %>
        </div>

        <div class="form-group">
          <h3><%= form.label :image %></h3>
          <%= form.text_field :image %>
          <h5><%= form.file_field :image, id: :image  %></h5>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1 class="text-center text-white" style="margin: 5rem 0 2rem 0;">Editing Product</h1>
<%= render 'form', product: @product %>
<div class="text-center">
  <h1><%= link_to 'Back', store_path(@store), class:'btn btn-light btn-lg'%></h1>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="container">
    <h1>Productos</h1>
    <table class="table">
      <thead class="table thead-light">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Image</th>
          <th>Price</th>
          <th>Store</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= image_tag product.image.to_s %></td>
            <td><%= product.price %></td>
            <td><%= product.store.name  %></td>
            <td><%= link_to 'Show', store_product_path(@store, product) %></td>
            <td><%= link_to 'Edit',edit_store_product_path(@store, product) %></td>
            <td><%= link_to 'Destroy', store_product_url(@store,product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Nuevo Producto', new_store_product_path %>
    <%= link_to 'Atras', stores_path(@store) %>

  </div>

</div>

app/views/products/new.html.erb
<h1 class="text-center text-white" style="margin: 5rem 0 2rem 0;">New Product</h1>
<%= render 'form', product: @product%>
<div class="text-center">
  <h1><%= link_to 'Back', store_path(@store), class:'btn btn-light btn-lg '%></h1>
</div>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Store:</strong>
  <%= @product.store.name %>
</p>

<%= link_to 'Edit', edit_store_product_url(@product) %> |
<%= link_to 'Back', store_products_path %>